### ISSUE TITLE
Changes needed to update RestAssured to 4.0.0

### ISSUE THREAD

**Issue by rdruss** [openshift-vertx-examples/vertx-crud-example-redhat#54]
```
[ERROR] testCreatingWithNoPayload(io.openshift.example.OpenShiftIT)  Time elapsed: 5.916 s <<< ERROR!
java.lang.NoClassDefFoundError: org/hamcrest/Matchers
        at io.openshift.example.OpenShiftIT.testCreatingWithNoPayload(OpenShiftIT.java:150)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matchers
        at io.openshift.example.OpenShiftIT.testCreatingWithNoPayload(OpenShiftIT.java:150)
```

**Comment by rdruss** [comment]
Current version of example uses RestAssured 4.3.0 - so upgrading to 4.x is no longer an issue.
